"""

Revision ID: 4b9cbcad8e64
Revises: 53acc91ada2d
Create Date: 2026-04-15 18:25:37.487320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b9cbcad8e64'
down_revision: Union[str, None] = '53acc91ada2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callback_configs',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('method', sa.Enum('POST', 'PUT', 'PATCH', name='callback_method_enum'), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('include_metadata', sa.Boolean(), nullable=False),
    sa.Column('batch_results', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['crawl_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callback_configs_created_at'), 'callback_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_callback_configs_schedule_id'), 'callback_configs', ['schedule_id'], unique=True)
    op.create_index(op.f('ix_callback_configs_updated_at'), 'callback_configs', ['updated_at'], unique=False)
    op.create_table('schedule_config_links',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['crawl_configurations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['crawl_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_config_links_config_id'), 'schedule_config_links', ['config_id'], unique=False)
    op.create_index(op.f('ix_schedule_config_links_created_at'), 'schedule_config_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_schedule_config_links_schedule_id'), 'schedule_config_links', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_config_links_updated_at'), 'schedule_config_links', ['updated_at'], unique=False)
    op.create_table('schedule_url_targets',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['crawl_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_url_targets_created_at'), 'schedule_url_targets', ['created_at'], unique=False)
    op.create_index(op.f('ix_schedule_url_targets_schedule_id'), 'schedule_url_targets', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_url_targets_updated_at'), 'schedule_url_targets', ['updated_at'], unique=False)
    op.create_table('callback_logs',
    sa.Column('callback_config_id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=True),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('request_url', sa.String(length=2000), nullable=False),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['callback_config_id'], ['callback_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['crawl_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callback_logs_callback_config_id'), 'callback_logs', ['callback_config_id'], unique=False)
    op.create_index(op.f('ix_callback_logs_crawl_job_id'), 'callback_logs', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_callback_logs_created_at'), 'callback_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_callback_logs_schedule_id'), 'callback_logs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_callback_logs_updated_at'), 'callback_logs', ['updated_at'], unique=False)
    op.add_column('crawl_schedules', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('crawl_schedules', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('crawl_schedules', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('crawl_schedules', sa.Column('run_count', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_crawl_schedules_crawl_configuration_id'), table_name='crawl_schedules')
    op.drop_constraint(op.f('crawl_schedules_crawl_configuration_id_fkey'), 'crawl_schedules', type_='foreignkey')
    op.drop_column('crawl_schedules', 'crawl_configuration_id')
    op.drop_column('crawl_schedules', 'target_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_schedules', sa.Column('target_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.add_column('crawl_schedules', sa.Column('crawl_configuration_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('crawl_schedules_crawl_configuration_id_fkey'), 'crawl_schedules', 'crawl_configurations', ['crawl_configuration_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_crawl_schedules_crawl_configuration_id'), 'crawl_schedules', ['crawl_configuration_id'], unique=False)
    op.drop_column('crawl_schedules', 'run_count')
    op.drop_column('crawl_schedules', 'last_run_at')
    op.drop_column('crawl_schedules', 'description')
    op.drop_column('crawl_schedules', 'name')
    op.drop_index(op.f('ix_callback_logs_updated_at'), table_name='callback_logs')
    op.drop_index(op.f('ix_callback_logs_schedule_id'), table_name='callback_logs')
    op.drop_index(op.f('ix_callback_logs_created_at'), table_name='callback_logs')
    op.drop_index(op.f('ix_callback_logs_crawl_job_id'), table_name='callback_logs')
    op.drop_index(op.f('ix_callback_logs_callback_config_id'), table_name='callback_logs')
    op.drop_table('callback_logs')
    op.drop_index(op.f('ix_schedule_url_targets_updated_at'), table_name='schedule_url_targets')
    op.drop_index(op.f('ix_schedule_url_targets_schedule_id'), table_name='schedule_url_targets')
    op.drop_index(op.f('ix_schedule_url_targets_created_at'), table_name='schedule_url_targets')
    op.drop_table('schedule_url_targets')
    op.drop_index(op.f('ix_schedule_config_links_updated_at'), table_name='schedule_config_links')
    op.drop_index(op.f('ix_schedule_config_links_schedule_id'), table_name='schedule_config_links')
    op.drop_index(op.f('ix_schedule_config_links_created_at'), table_name='schedule_config_links')
    op.drop_index(op.f('ix_schedule_config_links_config_id'), table_name='schedule_config_links')
    op.drop_table('schedule_config_links')
    op.drop_index(op.f('ix_callback_configs_updated_at'), table_name='callback_configs')
    op.drop_index(op.f('ix_callback_configs_schedule_id'), table_name='callback_configs')
    op.drop_index(op.f('ix_callback_configs_created_at'), table_name='callback_configs')
    op.drop_table('callback_configs')
    # ### end Alembic commands ###
