"""

Revision ID: 53c456acad12
Revises: f6a7b8c9d0e1
Create Date: 2026-04-19 22:04:02.453473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53c456acad12'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_notification_configs', 'recipient_emails',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of email addresses, e.g. ["user@example.com"]',
               existing_nullable=False)
    op.alter_column('email_notification_configs', 'subject_template',
               existing_type=sa.VARCHAR(length=500),
               comment='Subject line with optional {{var}} placeholders',
               existing_nullable=False)
    op.alter_column('email_notification_configs', 'batch_results',
               existing_type=sa.BOOLEAN(),
               comment='True = all results in one email; False = one per job',
               existing_nullable=False)
    op.alter_column('email_notification_configs', 'on_success',
               existing_type=sa.BOOLEAN(),
               comment='Send email when job succeeds',
               existing_nullable=False)
    op.alter_column('email_notification_configs', 'on_failure',
               existing_type=sa.BOOLEAN(),
               comment='Send email when job fails',
               existing_nullable=False)
    op.alter_column('email_notification_logs', 'recipients',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of email addresses sent to',
               existing_nullable=False)
    op.alter_column('email_notification_logs', 'trigger_reason',
               existing_type=sa.VARCHAR(length=32),
               comment='"success" or "failure"',
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'proxies_found',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'proxies_new',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'proxies_updated',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'proxies_truncated',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'content_length',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'duration_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_proxy_fetch_logs_created_at'), 'proxy_fetch_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_proxy_fetch_logs_updated_at'), 'proxy_fetch_logs', ['updated_at'], unique=False)
    op.alter_column('proxy_source_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_source_configs', 'require_all_urls',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_source_configs', 'validation_timeout',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_source_configs', 'fetch_interval_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_source_configs', 'proxy_ttl_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_proxy_source_configs_name'), table_name='proxy_source_configs')
    op.create_unique_constraint(None, 'proxy_source_configs', ['name'])
    op.alter_column('proxy_url_check_logs', 'proxies_tested',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_url_check_logs', 'proxies_passed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_url_check_logs', 'proxies_failed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_proxy_url_check_logs_created_at'), 'proxy_url_check_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_proxy_url_check_logs_updated_at'), 'proxy_url_check_logs', ['updated_at'], unique=False)
    op.alter_column('proxy_validation_logs', 'proxies_tested',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'proxies_healthy',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'proxies_degraded',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'proxies_unhealthy',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'proxies_removed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'duration_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_proxy_validation_logs_created_at'), 'proxy_validation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_proxy_validation_logs_updated_at'), 'proxy_validation_logs', ['updated_at'], unique=False)
    op.alter_column('schedule_proxy_source_links', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('schedule_proxy_source_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('schedule_proxy_source_links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_schedule_proxy_source_links_created_at'), 'schedule_proxy_source_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_schedule_proxy_source_links_updated_at'), 'schedule_proxy_source_links', ['updated_at'], unique=False)
    op.alter_column('valid_proxies', 'success_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('valid_proxies', 'failure_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valid_proxies', 'failure_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('valid_proxies', 'success_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_schedule_proxy_source_links_updated_at'), table_name='schedule_proxy_source_links')
    op.drop_index(op.f('ix_schedule_proxy_source_links_created_at'), table_name='schedule_proxy_source_links')
    op.alter_column('schedule_proxy_source_links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('schedule_proxy_source_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('schedule_proxy_source_links', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_proxy_validation_logs_updated_at'), table_name='proxy_validation_logs')
    op.drop_index(op.f('ix_proxy_validation_logs_created_at'), table_name='proxy_validation_logs')
    op.alter_column('proxy_validation_logs', 'duration_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'proxies_removed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'proxies_unhealthy',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'proxies_degraded',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'proxies_healthy',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_validation_logs', 'proxies_tested',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_proxy_url_check_logs_updated_at'), table_name='proxy_url_check_logs')
    op.drop_index(op.f('ix_proxy_url_check_logs_created_at'), table_name='proxy_url_check_logs')
    op.alter_column('proxy_url_check_logs', 'proxies_failed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_url_check_logs', 'proxies_passed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_url_check_logs', 'proxies_tested',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'proxy_source_configs', type_='unique')
    op.create_index(op.f('ix_proxy_source_configs_name'), 'proxy_source_configs', ['name'], unique=True)
    op.alter_column('proxy_source_configs', 'proxy_ttl_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('86400'),
               existing_nullable=False)
    op.alter_column('proxy_source_configs', 'fetch_interval_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3600'),
               existing_nullable=False)
    op.alter_column('proxy_source_configs', 'validation_timeout',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('proxy_source_configs', 'require_all_urls',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('proxy_source_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_proxy_fetch_logs_updated_at'), table_name='proxy_fetch_logs')
    op.drop_index(op.f('ix_proxy_fetch_logs_created_at'), table_name='proxy_fetch_logs')
    op.alter_column('proxy_fetch_logs', 'duration_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'content_length',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'proxies_truncated',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'proxies_updated',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'proxies_new',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('proxy_fetch_logs', 'proxies_found',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('email_notification_logs', 'trigger_reason',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='"success" or "failure"',
               existing_nullable=False)
    op.alter_column('email_notification_logs', 'recipients',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of email addresses sent to',
               existing_nullable=False)
    op.alter_column('email_notification_configs', 'on_failure',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Send email when job fails',
               existing_nullable=False)
    op.alter_column('email_notification_configs', 'on_success',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Send email when job succeeds',
               existing_nullable=False)
    op.alter_column('email_notification_configs', 'batch_results',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True = all results in one email; False = one per job',
               existing_nullable=False)
    op.alter_column('email_notification_configs', 'subject_template',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Subject line with optional {{var}} placeholders',
               existing_nullable=False)
    op.alter_column('email_notification_configs', 'recipient_emails',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of email addresses, e.g. ["user@example.com"]',
               existing_nullable=False)
    # ### end Alembic commands ###
