"""initial schema

Revision ID: 98fecaf91691
Revises: 
Create Date: 2026-04-14 20:14:41.448865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98fecaf91691'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_configurations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scraper_profile', sa.Enum('FETCHER', 'HTTP_SESSION', 'STEALTH', 'DYNAMIC', 'SPIDER', name='scraper_profile_enum'), nullable=False),
    sa.Column('fetch_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spider_entrypoint', sa.String(length=255), nullable=True),
    sa.Column('use_proxy', sa.Boolean(), nullable=False),
    sa.Column('rotate_user_agent', sa.Boolean(), nullable=False),
    sa.Column('custom_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_delay', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_crawl_configurations_created_at'), 'crawl_configurations', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawl_configurations_is_active'), 'crawl_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_crawl_configurations_scraper_profile'), 'crawl_configurations', ['scraper_profile'], unique=False)
    op.create_index(op.f('ix_crawl_configurations_updated_at'), 'crawl_configurations', ['updated_at'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('crawl_configuration_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='crawl_job_status_enum'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('queue', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_configuration_id'], ['crawl_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_crawl_jobs_celery_task_id'), 'crawl_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_crawl_configuration_id'), 'crawl_jobs', ['crawl_configuration_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_created_at'), 'crawl_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_queue'), 'crawl_jobs', ['queue'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_updated_at'), 'crawl_jobs', ['updated_at'], unique=False)
    op.create_table('crawl_schedules',
    sa.Column('crawl_configuration_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('default_queue', sa.String(length=64), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_configuration_id'], ['crawl_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_schedules_crawl_configuration_id'), 'crawl_schedules', ['crawl_configuration_id'], unique=False)
    op.create_index(op.f('ix_crawl_schedules_created_at'), 'crawl_schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawl_schedules_is_active'), 'crawl_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_crawl_schedules_next_run_at'), 'crawl_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_crawl_schedules_updated_at'), 'crawl_schedules', ['updated_at'], unique=False)
    op.create_table('crawl_job_results',
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_job_results_crawl_job_id'), 'crawl_job_results', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_crawl_job_results_created_at'), 'crawl_job_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawl_job_results_updated_at'), 'crawl_job_results', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_job_results_updated_at'), table_name='crawl_job_results')
    op.drop_index(op.f('ix_crawl_job_results_created_at'), table_name='crawl_job_results')
    op.drop_index(op.f('ix_crawl_job_results_crawl_job_id'), table_name='crawl_job_results')
    op.drop_table('crawl_job_results')
    op.drop_index(op.f('ix_crawl_schedules_updated_at'), table_name='crawl_schedules')
    op.drop_index(op.f('ix_crawl_schedules_next_run_at'), table_name='crawl_schedules')
    op.drop_index(op.f('ix_crawl_schedules_is_active'), table_name='crawl_schedules')
    op.drop_index(op.f('ix_crawl_schedules_created_at'), table_name='crawl_schedules')
    op.drop_index(op.f('ix_crawl_schedules_crawl_configuration_id'), table_name='crawl_schedules')
    op.drop_table('crawl_schedules')
    op.drop_index(op.f('ix_crawl_jobs_updated_at'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_queue'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_created_at'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_crawl_configuration_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_celery_task_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_crawl_configurations_updated_at'), table_name='crawl_configurations')
    op.drop_index(op.f('ix_crawl_configurations_scraper_profile'), table_name='crawl_configurations')
    op.drop_index(op.f('ix_crawl_configurations_is_active'), table_name='crawl_configurations')
    op.drop_index(op.f('ix_crawl_configurations_created_at'), table_name='crawl_configurations')
    op.drop_table('crawl_configurations')
    # ### end Alembic commands ###
