"""

Revision ID: f5e266ee1acd
Revises: 4b9cbcad8e64
Create Date: 2026-04-15 18:50:24.212858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e266ee1acd'
down_revision: Union[str, None] = '4b9cbcad8e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_url_targets', sa.Column('config_link_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_schedule_url_targets_schedule_id'), table_name='schedule_url_targets')
    op.create_index(op.f('ix_schedule_url_targets_config_link_id'), 'schedule_url_targets', ['config_link_id'], unique=False)
    op.drop_constraint(op.f('schedule_url_targets_schedule_id_fkey'), 'schedule_url_targets', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_url_targets', 'schedule_config_links', ['config_link_id'], ['id'], ondelete='CASCADE')
    op.drop_column('schedule_url_targets', 'schedule_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_url_targets', sa.Column('schedule_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'schedule_url_targets', type_='foreignkey')
    op.create_foreign_key(op.f('schedule_url_targets_schedule_id_fkey'), 'schedule_url_targets', 'crawl_schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_schedule_url_targets_config_link_id'), table_name='schedule_url_targets')
    op.create_index(op.f('ix_schedule_url_targets_schedule_id'), 'schedule_url_targets', ['schedule_id'], unique=False)
    op.drop_column('schedule_url_targets', 'config_link_id')
    # ### end Alembic commands ###
